### ISSUE TITLE
Feature request: Run from SDX commandline or RUNEXT

### ISSUE THREAD

**Issue by skrzyp** [epi/sapemu#1]
Add an ability to run SAPEmu from SpartaDOS X shell as commandline tool, like:

```
D3: SAPEMU D4:MUSIC\SOMETHING.SAP
```

Furthermore, `RUNEXT.SYS` interoperability can also be achieved in similar way.

In the era of SDX and Sparta Commander, that enhancements would be very helpful for users.

**Comment by epi** [comment]
Implemented in c488f500
